import { BarbarianCharacter } from '../player_character'

export const DefaultTestBarbarian: BarbarianCharacter = {
  level: 10,
  class: 'Barbarian',
  expertise: 'polearm',
  helmet: {
    modifiers: [
      ['armor', 25],
      ['core-skill-damage', 0.05],
      ['maximum-life', 20],
      ['attack-speed', 0.015],
    ],
  },
  chest: {
    aspect: ['devilish-aspect', [180]],
    modifiers: [
      //["all-stats", 2]
    ],
  },
  ring1: {
    modifiers: [
      ['cold-resistance', 0.15],
      ['critical-strike-chance', 0.05],
    ],
  },
  mainHand: {
    weaponType: 'sword',
    attackSpeed: 1.4,
    weaponDamage: 150,
    modifiers: [
      ['vulnerable-damage', 0.05],
      ['damage-to-close-enemies', 0.12],
      ['basic-skill-damage', 0.15],
    ],
  },
  offHand: {
    weaponType: 'axe',
    attackSpeed: 1.3,
    weaponDamage: 150,
    modifiers: [['overpower-damage', 0.1]],
  },
  twoHandedBludgeoning: {
    weaponType: 'two-handed-mace',
    attackSpeed: 0.8,
    weaponDamage: 280,
    modifiers: [
      ['vulnerable-damage', 0.05],
      ['damage-to-close-enemies', 0.12],
      ['basic-skill-damage', 0.15],
    ],
    aspect: ['aspect-of-the-iron-warrior', [0.1]],
  },
  twoHandedSlashing: {
    weaponType: 'two-handed-sword',
    attackSpeed: 0.8,
    weaponDamage: 350,
    modifiers: [
      ['vulnerable-damage', 0.05],
      ['damage-to-close-enemies', 0.12],
      ['basic-skill-damage', 0.15],
    ],
    aspect: ['gohrs-devastating-grips', [0.1]],
  },
  talents: {
    flay: 5,
    'enhanced-flay': 1,
    'battle-flay': 1,
    'combat-flay': 1,
    frenzy: 5,
    'enhanced-frenzy': 1,
    'battle-frenzy': 1,
    'combat-frenzy': 1,
    bash: 5,
    'enhanced-bash': 1,
    'battle-bash': 1,
    'combat-bash': 1,
    'lunging-strike': 5,
    'enhanced-lunging-strike': 1,
    'battle-lunging-strike': 1,
    'combat-lunging-strike': 1,
    whirlwind: 5,
    'enhanced-whirlwind': 1,
    'violent-whirlwind': 1,
    'furious-whirlwind': 1,
    'hammer-of-the-ancients': 5,
    'enhanced-hammer-of-the-ancients': 1,
    'violent-hammer-of-the-ancients': 1,
    'furious-hammer-of-the-ancients': 1,
    'pressure-point': 3,
    'endless-fury': 3,
    upheaval: 5,
    'enhanced-upheaval': 1,
    'violent-upheaval': 1,
    'furious-upheaval': 1,
    'double-swing': 5,
    'enhanced-double-swing': 1,
    'violent-double-swing': 1,
    'furious-double-swing': 1,
    rend: 5,
    'enhanced-rend': 1,
    'violent-rend': 1,
    'furious-rend': 1,
    'ground-stomp': 5,
    'enhanced-ground-stomp': 1,
    'tactical-ground-stomp': 1,
    'strategic-ground-stomp': 1,
    'rallying-cry': 5,
    'enhanced-rallying-cry': 1,
    'tactical-rallying-cry': 1,
    'strategic-rallying-cry': 1,
    'iron-skin': 5,
    'enhanced-iron-skin': 1,
    'tactical-iron-skin': 1,
    'strategic-iron-skin': 1,
    'challenging-shout': 5,
    'enhanced-challenging-shout': 1,
    'tactical-challenging-shout': 1,
    'strategic-challenging-shout': 1,
    'imposing-presence': 3,
    'martial-vigor': 3,
    outburst: 3,
    'tough-as-nails': 3,
    kick: 5,
    'enhanced-kick': 1,
    'mighty-kick': 1,
    'power-kick': 1,
    'war-cry': 5,
    'enhanced-war-cry': 1,
    'mighty-war-cry': 1,
    'power-war-cry': 1,
    charge: 5,
    'enhanced-charge': 1,
    'mighty-charge': 1,
    'power-charge': 1,
    leap: 5,
    'enhanced-leap': 1,
    'mighty-leap': 1,
    'power-leap': 1,
    swiftness: 3,
    'quick-impulses': 3,
    'booming-voice': 3,
    'raid-leader': 3,
    'guttural-yell': 3,
    'aggressive-resistance': 3,
    'battle-fervor': 3,
    'prolific-fury': 3,
    'death-blow': 5,
    'enhanced-death-blow': 1,
    'warriors-death-blow': 1,
    'fighters-death-blow': 1,
    rupture: 5,
    'enhanced-rupture': 1,
    'warriors-rupture': 1,
    'fighters-rupture': 1,
    'steel-grasp': 5,
    'enhanced-steel-grasp': 1,
    'warriors-steel-grasp': 1,
    'fighters-steel-grasp': 1,
    'pit-fighter': 3,
    'no-mercy': 3,
    'slaying-strike': 3,
    'expose-vulnerability': 3,
    hamstring: 3,
    'cut-to-the-bone': 3,
    'thick-skin': 3,
    'defensive-stance': 3,
    counteroffensive: 3,
    'call-of-the-ancients': 1,
    'prime-call-of-the-ancients': 1,
    'supreme-call-of-the-ancients': 1,
    'iron-maelstrom': 1,
    'prime-iron-maelstrom': 1,
    'supreme-iron-maelstrom': 1,
    'wrath-of-the-berserker': 1,
    'prime-wrath-of-the-berserker': 1,
    'supreme-wrath-of-the-berserker': 1,
    duelist: 3,
    'tempered-fury': 3,
    'furious-impulse': 3,
    'invigorating-fury': 3,
    'heavy-handed': 3,
    'brute-force': 3,
    wallop: 3,
    concussion: 3,
    unconstrained: 1,
    'walking-arsenal': 1,
    'unbridled-rage': 1,
    'gushing-wounds': 1,
  },
  toggles: {
    'enemy-spread-yards': 10,
    'number-of-enemies': 5,

    'percent-life': 0.5,
    'percent-barrier': 0.2,
    'world-tier': 3,
    'enemy-boss': false,
    'enemy-dazed': false,
    'enemy-elite': false,
    'enemy-stunned': false,
    'enemy-vulnerable': true,
    'enemy-chilled': false,
    'enemy-distant': false,
    'enemy-immobilized': false,
    'enemy-affected-by-shadow': false,
    'enemy-bleeding': false,
    'enemy-frozen': false,
    'enemy-burning': false,
    'enemy-knocked-down': false,
    'enemy-poisoned': false,
    'enemy-slowed': false,
    'altars-of-lilith-gathered': 100,
    berserking: true,
  },
  paragons: { powers: [] },
  abilities: [
    'hammer-of-the-ancients',
    'iron-maelstrom',
    'wrath-of-the-berserker',
    'frenzy',
    'iron-skin',
  ],
  vampiricPowers: [
    'accursed-touch',
    'anticipation',
    'bathe-in-blood',
    'blood-boil',
    'call-familiar',
    'covens-fangs',
    'domination',
    'feed-the-coven',
    'flowing-veins',
    'hectic',
    'hemomancy',
    'infection',
    'jagged-spikes',
    'metamorphosis',
    'moonrise',
    'prey-on-the-weak',
    'rampart',
    'ravenous',
    'resilience',
    'sanguine-brace',
    'terror',
    'undying',
  ],
}
