/* eslint-disable @typescript-eslint/no-unused-vars */
import {
  BarbarianCharacter,
  DruidCharacter,
  NecromancerCharacter,
  RogueCharacter,
  SorcererCharacter,
} from '../player_character'

export const TestWebsiteBug: NecromancerCharacter = {
  level: 100,
  class: 'Necromancer',
  helmet: {
    modifiers: [
      ['intelligence', 63],
      ['maximum-life', 1500],
      ['total-armor', 0.293],
      ['cooldown-reduction', 0.10400000000000001],
      ['maximum-life', 0.04],
      ['armor', 1187],
    ],
    aspect: ['viscous-aspect', []],
  },
  chest: {
    modifiers: [
      ['intelligence', 63],
      ['damage-reduction', 0.10800000000000001],
      ['total-armor', 0.293],
      ['physical-damage', 0.262],
      ['maximum-life', 0.04],
      ['maximum-life', 0.04],
      ['armor', 1662],
    ],
    aspect: ['blood-getters-aspect', []],
  },
  gloves: {
    modifiers: [
      ['critical-strike-chance', 0.12],
      ['intelligence', 63],
      ['lucky-hit-chance', 0.165],
      ['all-stats', 27],
      ['armor', 475],
    ],
    aspect: ['aspect-of-ultimate-shadow', [3579.456, 26249.344]],
  },
  pants: {
    modifiers: [
      ['damage', 0.26],
      ['damage-reduction-from-close-enemies', 0.2],
      ['maximum-resource', 19],
      ['potion-charges', 4],
      ['maximum-life', 0.04],
      ['maximum-life', 0.04],
      ['armor', 950],
    ],
    aspect: ['tibaults-will', [0.4]],
  },
  boots: {
    modifiers: [
      ['max-evade-charge', 3],
      ['intelligence', 63],
      ['movement-speed', 0.262],
      ['all-stats', 27],
      ['dodge-chance', 0.086],
      ['armor', 475],
    ],
    aspect: ['ghostwalker-aspect', [0.25]],
  },
  amulet: {
    modifiers: [
      ['resistance-to-all-elements', 0.24],
      ['ranks-of-the-amplify-damage-passive', 3],
      ['movement-speed', 0.262],
      ['cooldown-reduction', 0.10400000000000001],
      ['damage-reduction', 0.10800000000000001],
      ['resistance-to-all-elements', 0.05],
    ],
    aspect: ['aspect-of-grasping-veins', [0.2, 0.6000000000000001]],
  },
  ring1: {
    modifiers: [
      ['resistance-to-all-elements', 0.12],
      ['poison-resistance', 0.12],
      ['lucky-hit-chance', 0.09],
      ['maximum-life', 1500],
      ['maximum-essence', 18],
      ['ranks-of-all-corpse-skills', 3],
      ['resistance-to-all-elements', 0.05],
    ],
    aspect: ['ring-of-the-sacrilegious-soul', []],
  },
  ring2: {
    modifiers: [
      ['resistance-to-all-elements', 0.12],
      ['fire-resistance', 0.12],
      ['lucky-hit-chance', 0.09],
      ['maximum-minion-life', 0.47],
      ['minion-attack-speed', 0.21],
      ['thorns', 1410],
      ['armor', 250],
    ],
    aspect: ['ring-of-mendeln', [4]],
  },
  mainHand: {
    weaponType: 'wand',
    weaponDamage: 1686.6666666666667,
    attackSpeed: 1.2,
    modifiers: [
      ['lucky-hit-chance', 0.15000000000000002],
      ['intelligence', 78],
      ['all-stats', 42],
      ['critical-strike-damage', 0.315],
      ['vulnerable-damage', 0.293],
      ['critical-strike-damage-to-vulnerable-enemies', 0.12],
    ],
    aspect: ['blighted-aspect', [1.2]],
  },
  offHand: {
    weaponType: 'focus',
    weaponDamage: 1686.6666666666667,
    attackSpeed: 1.2,
    modifiers: [
      ['cooldown-reduction', 0.10353796680782201],
      ['lucky-hit-chance', 0.09],
      ['cooldown-reduction', 0.10400000000000001],
      ['intelligence', 63],
      ['critical-strike-chance', 0.075],
      ['critical-strike-damage-to-vulnerable-enemies', 0.12],
    ],
    aspect: ['blood-soaked-aspect', [2311.7320000000004]],
  },
  talents: {
    decompose: 1,
    'enhanced-decompose': 1,
    'unliving-energy': 1,
    'hewed-flesh': 3,
    'blood-mist': 5,
    'enhanced-blood-mist': 1,
    'ghastly-blood-mist': 1,
    'skeletal-warrior-mastery': 3,
    'grim-harvest': 1,
    'fueled-by-death': 3,
    'corpse-explosion': 1,
    'enhanced-corpse-explosion': 1,
    'blighted-corpse-explosion': 1,
    'deaths-embrace': 3,
    'amplify-damage': 3,
    decrepify: 1,
    'enhanced-decrepify': 1,
    'abhorrent-decrepify': 1,
    'corpse-tendrils': 1,
    'enhanced-corpse-tendrils': 1,
    'plagued-corpse-tendrils': 1,
    'necrotic-carapace': 3,
    'reapers-pursuit': 3,
    gloom: 3,
    'inspiring-leader': 3,
    'deaths-defense': 3,
    'bone-storm': 1,
    'prime-bone-storm': 1,
    'supreme-bone-storm': 1,
    shadowblight: 1,
  },
  toggles: {
    'enemy-boss': false,
    'enemy-dazed': false,
    'enemy-elite': false,
    'enemy-stunned': false,
    'enemy-vulnerable': false,
    'enemy-chilled': false,
    'enemy-distant': false,
    'enemy-immobilized': false,
    'enemy-affected-by-shadow': false,
    'enemy-bleeding': false,
    'enemy-frozen': false,
    'enemy-burning': false,
    'enemy-knocked-down': false,
    'enemy-poisoned': false,
    'enemy-slowed': false,
    'percent-life': 1,
    'percent-fortify': 0,
    'percent-barrier': 0,
    'number-of-enemies': 1,
    'enemy-spread-yards': 25,
    'altars-of-lilith-gathered': 160,
    'world-tier': 4,
    berserking: false,
  },
  paragons: {
    attributes: {
      dexterity: 311,
      intelligence: 465,
      strength: 95,
      willpower: 242,
    },
    modifiers: [
      ['damage-to-injured-enemies', 0.125],
      ['damage-to-injured-enemies', 0.125],
      ['damage-to-injured-enemies', 0.25],
      ['critical-strike-damage', 0.15],
      ['critical-strike-damage', 0.075],
      ['damage-to-injured-enemies', 0.125],
      ['critical-strike-damage', 0.075],
      ['damage-to-elites', 0.2],
      ['damage-to-elites', 0.2],
      ['damage-to-elites', 0.2],
      ['resistance-to-all-elements', 0.038],
      ['resistance-to-all-elements', 0.038],
      ['resistance-to-all-elements', 0.03],
      ['damage-to-elites', 0.16],
      ['damage-to-affected-by-shadow-damage-over-time-enemies', 0.05],
      ['damage-to-elites', 0.08],
      ['damage-to-affected-by-shadow-damage-over-time-enemies', 0.1],
      ['damage-to-elites', 0.16],
      ['damage-to-affected-by-shadow-damage-over-time-enemies', 0.05],
      ['damage-to-affected-by-shadow-damage-over-time-enemies', 0.05],
      ['damage-to-elites', 0.08],
      ['critical-strike-damage', 0.772],
      ['shadow-resistance', 0.1],
      ['vulnerable-damage', 0.392],
      ['damage-while-fortified', 0.05],
      ['damage-while-fortified', 0.1],
      ['damage-reduction-for-your-minions', 0.1],
      ['damage-reduction-for-your-minions', 0.2],
      ['damage-reduction-for-your-minions', 0.1],
      ['damage-reduction-for-your-minions', 0.1],
      ['minion-damage', 0.1],
      ['minion-damage', 0.2],
      ['damage-to-healthy-enemies', 0.125],
      ['critical-strike-damage', 0.075],
      ['damage-to-healthy-enemies', 0.25],
      ['critical-strike-damage', 0.15],
      ['damage-to-healthy-enemies', 0.125],
      ['critical-strike-damage', 0.075],
      ['damage-to-healthy-enemies', 0.125],
      ['damage-while-healthy', 1.354],
      ['damage-to-injured-enemies', 0.125],
      ['damage-to-injured-enemies', 0.125],
      ['damage-to-injured-enemies', 0.25],
      ['damage-to-injured-enemies', 0.125],
      ['armor', 50],
      ['armor', 100],
      ['critical-strike-damage', 0.075],
      ['critical-strike-damage', 0.075],
      ['critical-strike-damage', 0.075],
      ['critical-strike-damage', 0.15],
      ['potion-healing', 0.04],
      ['armor', 50],
      ['armor', 50],
      ['damage', 0.05],
      ['damage', 0.1],
      ['%-maximum-life', 0.04],
      ['%-maximum-life', 0.02],
      ['damage', 0.05],
      ['armor', 125],
      ['armor', 100],
      ['armor', 125],
      ['resistance-to-all-elements', 0.015],
      ['%-maximum-life', 0.02],
      ['resistance-to-all-elements', 0.03],
      ['%-maximum-life', 0.04],
      ['damage', 0.125],
      ['damage', 0.1],
      ['damage', 0.125],
      ['damage', 0.125],
      ['armor', 125],
      ['%-maximum-life', 0.02],
      ['%-maximum-life', 0.02],
      ['damage-to-injured-enemies', 0.25],
      ['resistance-to-all-elements', 0.03],
      ['damage-to-elites', 0.16],
      ['damage-to-affected-by-shadow-damage-over-time-enemies', 0.1],
      ['shadow-resistance', 0.1],
      ['damage-while-fortified', 0.1],
      ['damage-to-healthy-enemies', 0.25],
      ['damage-to-injured-enemies', 0.25],
      ['armor', 100],
      ['critical-strike-damage', 0.15],
      ['damage', 0.1],
      ['armor', 100],
      ['resistance-to-all-elements', 0.03],
      ['damage', 0.1],
    ],
    powers: [
      'flesh-eater',
      'scent-of-death',
      'amplify',
      'essence',
      'exploit',
      'deadraiser',
      'imbiber',
      'corporeal',
    ],
  },
  vampiricPowers: [
    'metamorphosis',
    'anticipation',
    'feed-the-coven',
    'prey-on-the-weak',
    'resilience',
  ],

  abilities: [
    'raise-skeleton',
    'bone-storm',
    'blood-mist',
    'corpse-tendrils',
    'decrepify',
    'corpse-explosion',
  ],
  bookOfTheDead: {
    skeletalWarriors: ['skirmishers', 1],
    skeletalMages: ['shadow', 2],
    golem: ['iron', 3],
  },
}
